---
- name: Python
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  vars_prompt:
    - name: 'python_selection'
      prompt: "Please choose the number for Python version [ 1/2/3]\n 
      1: python3.6\n 
      2: python3.7(only for ubuntu)\n
      3: python3.8\n
      4: python3.9\n"
      private: no
      default: 1

  vars:
    python_select:
      '1': "3.6"
      '2': "3.7"
      '3': "3.8"
      '4': "3.9"

    python_applications:
      - django
    python_version: "{{python_select[python_selection]}}"

pre_tasks:
   - debug: var=python_version

  roles:
  - { role: role_common , tags: "role_common"}
  - { role: role_cloud, tags: "role_cloud"} 
  - { role: role_nginx , tags: "role_nginx"}
  - { role: role_sqlite , tags: "role_sqlite"}
  - { role: role_python , tags: "role_python"}
  - { role: role_mysql , tags: "role_mysql"}
  - { role: role_9panel , tags: "9panel"} 
  - { role: role_docker , tags: "role_docker"} 
  - { role: role_init , tags: "role_init"} 
  - { role: role_preend , tags: "role_preend"} 
  - { role: role_end , tags: "role_end"} 
