- src: http://github.com/websoft9dev/role_common

- src: http://github.com/websoft9dev/role_cloud

- src: http://github.com/websoft9dev/role_nginx

- src: http://github.com/websoft9dev/role_sqlite

- src: http://github.com/websoft9dev/role_python

- src: http://github.com/websoft9dev/role_9panel

- src: http://github.com/websoft9dev/role_mysql

- src: http://github.com/websoft9dev/role_docker

- src: http://github.com/websoft9dev/role_redis

- src: http://github.com/websoft9dev/role_init

- src: http://github.com/websoft9dev/role_preend

- src: http://github.com/websoft9dev/role_end
