- name: Use pip3 install PyMySQL
  pip: 
    name: pymysql
    executable: pip3

- name: Insert mysql connection
  blockinfile:
  path: "{{python_venv_path}}/{{python_applications}}/django_project/django_project/__init__.py"
  block: |
    import pymysql
    pymysql.install_as_MySQLdb()

- name: Remove sqlite3  configure
  blockinfile:
  path: "{{python_venv_path}}/{{python_applications}}/django_project/django_project/settings.py"
  state: absent
  block: |
    DATABASES = {
​      'default': {
​      'ENGINE': 'django.db.backends.sqlite3',
​      'NAME': BASE_DIR / 'db.sqlite3',
​      }
    }
 
- name: Adding MySQL as the default database
  blockinfile:
  path: "{{python_venv_path}}/{{python_applications}}/django_project/django_project/settings.py"
  insertafter: "#.*#databases"
  block: |
    DATABASES = {
​      'default': {
​        'ENGINE': 'django.db.backends.mysql',
​        'NAME': 'django',
​        'USER': 'django',
​        'PASSWORD': '{{mysql_root_password}}',
​        'HOST': '127.0.0.1',
​        'PORT': '3306',
​      }
    }