- name: Use pip3 install PyMySQL
  pip:
    name: pymysql
    executable: pip3

- name: Remove sqlite3 configure
  shell: sed -i '/DATABASES = {/,+9d' /data/apps/django/django_project/django_project/settings.py
  
- name: Import pymysql module
  blockinfile:
    path: /data/apps/django/django_project/django_project/__init__.py
    block: |
      import pymysql
      pymysql.install_as_MySQLdb()

- name: Adding MySQL as the default database
  shell: 
    cmd: |
      cat <<EOF |sudo tee -a /data/apps/django/django_project/django_project/settings.py
      DATABASES = {
          'default': {
              'ENGINE': 'django.db.backends.mysql',
              'NAME': 'django',
              'USER': 'django',
              'PASSWORD': '{{mysql_root_password}}',
              'HOST': '127.0.0.1',
              'PORT': '3306',
          }
      }
      EOF
